server:
  port: 8083

spring:
  application:
    name: analysis-service
  datasource:
    url: jdbc:mysql://localhost:3306/analysis_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

analysis:
  etl:
    profile-calc-rate: 60000 # 用户画像计算间隔，单位毫秒，默认1分钟
    stats-granularity: MINUTES # 聚合粒度: HOURS 或 MINUTES
