server:
  port: 8081

spring:
  application:
    name: viewer-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 请确保数据库 db_viewer 已经由之前的 SQL 脚本创建
    url: jdbc:mysql://localhost:3306/db_viewer?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root        # 修改为你的数据库账号
    password: 247365    # 修改为你的数据库密码

  # Redis 配置
  redis:
    host: localhost
    port: 6379

  # Consul 配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 在控制台打印 SQL，方便调试

# 日志配置 (配合 Common 模块的 TraceId)
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{traceId}] - %msg%n"